In [1]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [2]:
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [3]:
x = torch.tensor([False, 1, 2.0])
print(x)
# tensor([0., 1., 2.])

tensor([0., 1., 2.])


In [4]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
torch.randint(low=0, high=10, size=(3,4))

tensor([[7, 1, 6, 7],
        [4, 9, 7, 3],
        [5, 7, 3, 2]])

In [7]:
torch.rand(3, 4)

tensor([[0.8627, 0.8123, 0.2920, 0.5902],
        [0.1630, 0.6015, 0.1532, 0.9644],
        [0.5040, 0.6781, 0.1845, 0.7558]])

In [8]:
torch.randn((3,4))

tensor([[ 0.3510,  1.1779, -0.8924, -0.6351],
        [ 1.7297,  0.0967, -0.0507,  0.0762],
        [-0.0810, -0.8379,  0.4826, -1.3563]])

In [9]:
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
